name: CI
on:
  push:
    branches:
      - master
      - develop
      - containerization
  pull_request:

jobs:
  compile:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: Dockerfile
          sparse-checkout-cone-mode: false
      - uses: docker/setup-buildx-action@v3
      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          tags: ci-environ
          outputs: type=docker,dest=/tmp/ci-environ.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ci-environ
          path: /tmp/ci-environ.tar
  test:
    needs: compile
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: ci-environ
          path: /tmp
      - name: Load image
        run: docker load --input /tmp/ci-environ.tar
      - name: Run container
        run: docker run --interactive --name ci-environ environ-image
      - name: Access container
        run: docker exec --interactive --tty ci-environ bash
      - name: Run tests
        run: cd q-e/Environ/tests && make --ignore-errors run-tests-parallel
